#ifndef KPRCB_H
#define KPRCB_H

#include "kernel_structs.h"

struct _KPRCB {
    unsigned int MxCsr;
    unsigned __int8 LegacyNumber;
    unsigned __int8 ReservedMustBeZero;
    unsigned __int8 InterruptRequest;
    unsigned __int8 IdleHalt;
    _KTHREAD* CurrentThread;
    _KTHREAD* NextThread;
    _KTHREAD* IdleThread;
    unsigned __int8 NestingLevel;
    unsigned __int8 ClockOwner;
    unsigned __int16 __u10;
    unsigned __int8 IdleState;
    unsigned int Number;
    unsigned __int64 RspBase;
    unsigned __int64 PrcbLock;
    char* PriorityState;
    char CpuType;
    char CpuID;
    unsigned __int8 __u18[5];
    unsigned int MHz;
    unsigned __int64 HalReserved[8];
    unsigned __int16 MinorVersion;
    unsigned __int16 MajorVersion;
    unsigned __int8 BuildType;
    unsigned __int8 CpuVendor;
    unsigned __int8 LegacyCoresPerPhysicalProcessor;
    unsigned __int8 LegacyLogicalProcessorsPerCore;
    unsigned __int64 TscFrequency;
    unsigned int CoresPerPhysicalProcessor;
    unsigned int LogicalProcessorsPerCore;
    unsigned __int64 PrcbPad04[4];
    _KNODE* ParentNode;
    unsigned __int64 GroupSetMember;
    unsigned __int8 Group;
    unsigned __int8 GroupIndex;
    unsigned __int8 PrcbPad05[2];
    unsigned int InitialApicId;
    unsigned int ScbOffset;
    unsigned int ApicMask;
    void* AcpiReserved;
    unsigned int CFlushSize;
    _KPRCBFLAG PrcbFlags;
    unsigned int __u42;
    _KPROCESSOR_STATE ProcessorState;
    _XSAVE_AREA_HEADER* ExtendedSupervisorState;
    unsigned int ProcessorSignature;
    unsigned int ProcessorFlags;
    unsigned __int64 __u47;
    unsigned __int64 PrcbPad12[3];
    _KSPIN_LOCK_QUEUE LockQueue[17];
    _PP_LOOKASIDE_LIST PPLookasideList[16];
    _GENERAL_LOOKASIDE_POOL PPNxPagedLookasideList[32];
    _GENERAL_LOOKASIDE_POOL PPNPagedLookasideList[32];
    _GENERAL_LOOKASIDE_POOL PPPagedLookasideList[32];
    unsigned __int64 MsrIa32TsxCtrl;
    _SINGLE_LIST_ENTRY DeferredReadyListHead;
    volatile int MmPageFaultCount;
    volatile int MmCopyOnWriteCount;
    volatile int MmTransitionCount;
    volatile int MmDemandZeroCount;
    volatile int MmPageReadCount;
    volatile int MmPageReadIoCount;
    volatile int MmDirtyPagesWriteCount;
    volatile int MmDirtyWriteIoCount;
    volatile int MmMappedPagesWriteCount;
    volatile int MmMappedWriteIoCount;
    unsigned int KeSystemCalls;
    unsigned int KeContextSwitches;
    unsigned int PrcbPad40;
    unsigned int CcFastReadNoWait;
    unsigned int CcFastReadWait;
    unsigned int CcFastReadNotPossible;
    unsigned int CcCopyReadNoWait;
    unsigned int CcCopyReadWait;
    unsigned int CcCopyReadNoWaitMiss;
    volatile int IoReadOperationCount;
    volatile int IoWriteOperationCount;
    volatile int IoOtherOperationCount;
    _LARGE_INTEGER IoReadTransferCount;
    _LARGE_INTEGER IoWriteTransferCount;
    _LARGE_INTEGER IoOtherTransferCount;
    volatile int PacketBarrier;
    volatile int TargetCount;
    volatile unsigned int IpiFrozen;
    unsigned int PrcbPad30;
    void* IsrDpcStats;
    unsigned int DeviceInterrupts;
    int LookasideIrpFloat;
    unsigned int InterruptLastCount;
    unsigned int InterruptRate;
    unsigned __int64 PrcbPad31;
    _KPRCB* PairPrcb;
    _KSTATIC_AFFINITY_BLOCK StaticAffinity;
    unsigned __int64 PrcbPad35[5];
    _SLIST_HEADER InterruptObjectPool;
    _RTL_HASH_TABLE* DpcRuntimeHistoryHashTable;
    _KDPC* DpcRuntimeHistoryHashTableCleanupDpc;
    void(__fastcall* CurrentDpcRoutine)(_KDPC*, void*, void*, void*);
    unsigned __int64 CurrentDpcRuntimeHistoryCached;
    unsigned __int64 CurrentDpcStartTime;
    unsigned __int64 PrcbPad41[1];
    _KDPC_DATA DpcData[2];
    void* DpcStack;
    int MaximumDpcQueueDepth;
    unsigned int DpcRequestRate;
    unsigned int MinimumDpcRate;
    unsigned int DpcLastCount;
    unsigned __int8 ThreadDpcEnable;
    volatile unsigned __int8 QuantumEnd;
    volatile unsigned __int8 DpcRoutineActive;
    volatile unsigned __int8 IdleSchedule;
    unsigned int __u111;
    unsigned int PrcbPad93;
    unsigned int LastTick;
    unsigned int ClockInterrupts;
    unsigned int ReadyScanTick;
    void* InterruptObject[256];
    _KTIMER_TABLE TimerTable;
    unsigned int PrcbPad92[10];
    _KGATE DpcGate;
    void* PrcbPad52;
    _KDPC CallDpc;
    int ClockKeepAlive;
    unsigned __int8 PrcbPad60[2];
    unsigned __int16 __u124;
    int DpcWatchdogPeriod;
    int DpcWatchdogCount;
    volatile int KeSpinLockOrdering;
    unsigned int DpcWatchdogProfileCumulativeDpcThreshold;
    void* CachedPtes;
    _LIST_ENTRY WaitListHead;
    unsigned __int64 WaitLock;
    unsigned int ReadySummary;
    int AffinitizedSelectionMask;
    unsigned int QueueIndex;
    unsigned int PrcbPad75[2];
    unsigned int DpcWatchdogSequenceNumber;
    _KDPC TimerExpirationDpc;
    _RTL_RB_TREE ScbQueue;
    _LIST_ENTRY DispatcherReadyListHead[32];
    unsigned int InterruptCount;
    unsigned int KernelTime;
    unsigned int UserTime;
    unsigned int DpcTime;
    unsigned int InterruptTime;
    unsigned int AdjustDpcThreshold;
    unsigned __int8 DebuggerSavedIRQL;
    unsigned __int8 GroupSchedulingOverQuota;
    volatile unsigned __int8 DeepSleep;
    unsigned __int8 PrcbPad80;
    unsigned int DpcTimeCount;
    unsigned int DpcTimeLimit;
    unsigned int PeriodicCount;
    unsigned int PeriodicBias;
    unsigned int AvailableTime;
    unsigned int KeExceptionDispatchCount;
    unsigned int ReadyThreadCount;
    unsigned __int64 ReadyQueueExpectedRunTime;
    unsigned __int64 StartCycles;
    unsigned __int64 TaggedCyclesStart;
    unsigned __int64 TaggedCycles[3];
    unsigned __int64 AffinitizedCycles;
    unsigned __int64 ImportantCycles;
    unsigned __int64 UnimportantCycles;
    unsigned int DpcWatchdogProfileSingleDpcThreshold;
    volatile int MmSpinLockOrdering;
    void* volatile CachedStack;
    unsigned int PageColor;
    unsigned int NodeColor;
    unsigned int NodeShiftedColor;
    unsigned int SecondaryColorMask;
    unsigned __int8 PrcbPad81[6];
    unsigned __int8 ExceptionStackActive;
    unsigned __int8 TbFlushListActive;
    void* ExceptionStack;
    unsigned __int64 PrcbPad82[1];
    unsigned __int64 CycleTime;
    unsigned __int64 Cycles[4][2];
    unsigned int CcFastMdlReadNoWait;
    unsigned int CcFastMdlReadWait;
    unsigned int CcFastMdlReadNotPossible;
    unsigned int CcMapDataNoWait;
    unsigned int CcMapDataWait;
    unsigned int CcPinMappedDataCount;
    unsigned int CcPinReadNoWait;
    unsigned int CcPinReadWait;
    unsigned int CcMdlReadNoWait;
    unsigned int CcMdlReadWait;
    unsigned int CcLazyWriteHotSpots;
    unsigned int CcLazyWriteIos;
    unsigned int CcLazyWritePages;
    unsigned int CcDataFlushes;
    unsigned int CcDataPages;
    unsigned int CcLostDelayedWrites;
    unsigned int CcFastReadResourceMiss;
    unsigned int CcCopyReadWaitMiss;
    unsigned int CcFastMdlReadResourceMiss;
    unsigned int CcMapDataNoWaitMiss;
    unsigned int CcMapDataWaitMiss;
    unsigned int CcPinReadNoWaitMiss;
    unsigned int CcPinReadWaitMiss;
    unsigned int CcMdlReadNoWaitMiss;
    unsigned int CcMdlReadWaitMiss;
    unsigned int CcReadAheadIos;
    volatile int MmCacheTransitionCount;
    volatile int MmCacheReadCount;
    volatile int MmCacheIoCount;
    unsigned int PrcbPad91;
    void* MmInternal;
    _PROCESSOR_POWER_STATE PowerState;
    void* HyperPte;
    _LIST_ENTRY ScbList;
    _KDPC ForceIdleDpc;
    _KDPC DpcWatchdogDpc;
    _KTIMER DpcWatchdogTimer;
    _CACHE_DESCRIPTOR Cache[5];
    unsigned int CacheCount;
    volatile unsigned int CachedCommit;
    volatile unsigned int CachedResidentAvailable;
    void* WheaInfo;
    void* EtwSupport;
    void* ExSaPageArray;
    unsigned int KeAlignmentFixupCount;
    unsigned int PrcbPad95;
    _SLIST_HEADER HypercallPageList;
    unsigned __int64* StatisticsPage;
    unsigned __int64 GenerationTarget;
    unsigned __int64 PrcbPad85[4];
    void* HypercallCachedPages;
    void* VirtualApicAssist;
    _KAFFINITY_EX PackageProcessorSet;
    unsigned int PackageId;
    unsigned int PrcbPad86;
    unsigned __int64 SharedReadyQueueMask;
    _KSHARED_READY_QUEUE* SharedReadyQueue;
};

#endif //KPRCB_H
